#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct 25 22:58:11 2019

@author: albertlu
"""
'''
Install all of these
!pip install beautifulsoup4
!pip install requests
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
!pip install selenium'''

import numpy as np
import pandas as pd
import requests
import bs4
import lxml.etree as xml

from selenium import webdriver
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

options = webdriver.ChromeOptions()
options.add_argument("user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36")
options.add_argument("--headless")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

URL = "https://www.bloomingdales.com/shop/search?keyword=red+jeans"

# Put the chrome executable in the folder

wd = webdriver.Chrome("./chromedriver", options=options)
timeout = 20
wd.implicitly_wait(timeout)
    
wd.get(URL)

web_page = bs4.BeautifulSoup(wd.page_source, "lxml")
sub_web_page = web_page.find_all("span", class_="brand")
sub_web_page = web_page.find_all("div", class_="productDescription")

print()
# class="product-price__highlight
for i in sub_web_page:
    print(i.text)
