#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct 25 22:58:11 2019

@author: albertlu
"""
'''
Install all of these
!pip install beautifulsoup4
!pip install requests
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
!pip install selenium'''

import numpy as np
import pandas as pd
import requests
import bs4
import lxml.etree as xml

from selenium import webdriver
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

def get_webdriver() -> webdriver:
    options = webdriver.ChromeOptions()
    options.add_argument("--headless")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36")
    wd = webdriver.Chrome("./chromedriver", options=options)
    timeout = 30
    wd.implicitly_wait(timeout)
    return wd

def search_bloomingdales(*keywords):
    URL = "https://www.bloomingdales.com/shop/search?keyword="
    print(URL)
    KEYWORD_STRING = "+".join(keywords)
    URL += KEYWORD_STRING
    print(URL)
    wd = get_webdriver()
    wd.get(URL)
    web_page = bs4.BeautifulSoup(wd.page_source, "lxml")
    descriptions = web_page.find_all("div", class_="productDescription")
    return descriptions
for i in search_bloomingdales("red", "jeans"):
    print(i.text)